select                                                                                                                                                                                                                                                                                                                                                                     
    tcp.rtt,
    eswithmetro(tcp.clientip) clientmetro                                                                                                                                                                                                                                                                                                                                                           
from                                                                                                                                                                                                                                                                                                                                                                       
    (                                                                                                                                                                                                                                                                                                                                                                      
        select                                                                                                                                                                                                                                                                                                                                                             
            tcp_smoothed_rtt rtt,                                                                                                                                                                                                                                                                                                                                          
            ghostregion,
            clientip                                                                                                                                                                                                                                                                                                                                                  
        from                                                                                                                                                                                                                                                                                                                                                               
            tcpstats_v7                                                                                                                                                                                                                                                                                                                                                    
        where                                                                                                                                                                                                                                                                                                                                                              
            pdate = '$dt'                                                                                                                                                                                                                                                                                                                                                  
            and (                                                                                                                                                                                                                                                                                                                                                          
                ak_maprule like '%dscw80'                                                                                                                                                                                                                                                                                                                                  
                or ak_maprule like 'w80'                                                                                                                                                                                                                                                                                                                                   
            )                                                                                                                                                                                                                                                                                                                                                              
            and  = '$from'                                                                                                                                                                                                                                                                                                                  
            and sampling_rate = 0.001                                                                                                                                                                                                                                                                                                                                      
            and enduser = 1                                                                                                                                                                                                                                                                                                                                                
    ) tcp,                                                                                                                                                                                                                                                                                                                                                                 
    (                                                                                                                                                                                                                                                                                                                                                                      
        select                                                                                                                                                                                                                                                                                                                                                             
            region                                                                                                                                                                                                                                                                                                                                                         
        from                                                                                                                                                                                                                                                                                                                                                               
            m2regions_now                                                                                                                                                                                                                                                                                                                                                  
        where                                                                                                                                                                                                                                                                                                                                                              
            region_metro = '$to'                                                                                                                                                                                                                                                                                                                                           
            and numghosts > 0                                                                                                                                                                                                                                                                                                                                              
            and region != 44442                                                                                                                                                                                                                                                                                                                                            
            and service = 'W'                                                                                                                                                                                                                                                                                                                                              
    ) b,                                                                                                                                                                                                                                                                                                                                                                   
    (                                                                                                                                                                                                                                                                                                                                                                      
        select                                                                                                                                                                                                                                                                                                                                                             
            region                                                                                                                                                                                                                                                                                                                                                         
        from                                                                                                                                                                                                                                                                                                                                                               
            mcm_machines                                                                                                                                                                                                                                                                                                                                                   
        where                                                                                                                                                                                                                                                                                                                                                              
            pkey = '$dt'                                                                                                                                                                                                                                                                                                                                                   
            and (                                                                                                                                                                                                                                                                                                                                                          
                hardwaretype like '%SSD%'                                                                                                                                                                                                                                                                                                                                  
                or hardwaretype like '%NVME%'                                                                                                                                                                                                                                                                                                                              
            )                                                                                                                                                                                                                                                                                                                                                              
            and region != 44442                                                                                                                                                                                                                                                                                                                                            
            and network = 'freeflow'                                                                                                                                                                                                                                                                                                                                       
        group by                                                                                                                                                                                                                                                                                                                                                           
            region                                                                                                                                                                                                                                                                                                                                                         
    ) c                                                                                                                                                                                                                                                                                                                                                                    
where                                                                                                                                                                                                                                                                                                                                                                      
    tcp.ghostregion = b.region                                                                                                                                                                                                                                                                                                                                             
    and tcp.ghostregion = c.region                  